name: Updater (WIP)

on:
  schedule:
    - cron: 0 0 * * 0

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4 # Used to install node environment - XXX https://github.com/actions/setup-node
        with:
          node-version: 20
      #- uses: wowchemy/gh-action-updater@v1
      #  with:
      #    feed-url: https://wowchemy.com/blog/index.xml
      #    readme-section: news
